console.log(5 > 2 )
console.log(5 < 2)
console.log( 5 >= 5)
console.log( 5 >= 4)
console.log( 5 >= 6)
console.log( 5 <= 4)
console.log(4 != 4 )
console.log( 5 === 5)
console.log( 5 == 4)
console.log( "Deus" == "Deus" )
console.log( "Deus" === "Dfus" )
console.log( "Deus" != "Deus" )